CREATE TABLE IF NOT EXISTS offer_categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('approved', 'pending', 'rejected')) DEFAULT 'pending',
    requested_by_user_id INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TEXT,
    reviewed_by_user_id INTEGER,
    FOREIGN KEY (requested_by_user_id) REFERENCES users (id),
    FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_offer_categories_status ON offer_categories (status, name);

INSERT OR IGNORE INTO offer_categories (name, normalized_name, status, created_at)
VALUES
    ('Almacén', lower(trim('Almacén')), 'approved', CURRENT_TIMESTAMP),
    ('Bazar', lower(trim('Bazar')), 'approved', CURRENT_TIMESTAMP),
    ('Carnicería', lower(trim('Carnicería')), 'approved', CURRENT_TIMESTAMP),
    ('Verdulería', lower(trim('Verdulería')), 'approved', CURRENT_TIMESTAMP),
    ('Panadería', lower(trim('Panadería')), 'approved', CURRENT_TIMESTAMP),
    ('Pastelería', lower(trim('Pastelería')), 'approved', CURRENT_TIMESTAMP),
    ('Fiambrería', lower(trim('Fiambrería')), 'approved', CURRENT_TIMESTAMP),
    ('Dietética', lower(trim('Dietética')), 'approved', CURRENT_TIMESTAMP),
    ('Vinoteca', lower(trim('Vinoteca')), 'approved', CURRENT_TIMESTAMP),
    ('Cervecería artesanal', lower(trim('Cervecería artesanal')), 'approved', CURRENT_TIMESTAMP),
    ('Gastronomía', lower(trim('Gastronomía')), 'approved', CURRENT_TIMESTAMP),
    ('Comida rápida', lower(trim('Comida rápida')), 'approved', CURRENT_TIMESTAMP),
    ('Heladería', lower(trim('Heladería')), 'approved', CURRENT_TIMESTAMP),
    ('Cafetería', lower(trim('Cafetería')), 'approved', CURRENT_TIMESTAMP),
    ('Restaurant', lower(trim('Restaurant')), 'approved', CURRENT_TIMESTAMP),
    ('Pizzería', lower(trim('Pizzería')), 'approved', CURRENT_TIMESTAMP),
    ('Parrilla', lower(trim('Parrilla')), 'approved', CURRENT_TIMESTAMP),
    ('Farmacia', lower(trim('Farmacia')), 'approved', CURRENT_TIMESTAMP),
    ('Perfumería', lower(trim('Perfumería')), 'approved', CURRENT_TIMESTAMP),
    ('Óptica', lower(trim('Óptica')), 'approved', CURRENT_TIMESTAMP),
    ('Indumentaria', lower(trim('Indumentaria')), 'approved', CURRENT_TIMESTAMP),
    ('Calzado', lower(trim('Calzado')), 'approved', CURRENT_TIMESTAMP),
    ('Marroquinería', lower(trim('Marroquinería')), 'approved', CURRENT_TIMESTAMP),
    ('Joyería', lower(trim('Joyería')), 'approved', CURRENT_TIMESTAMP),
    ('Librería', lower(trim('Librería')), 'approved', CURRENT_TIMESTAMP),
    ('Juguetería', lower(trim('Juguetería')), 'approved', CURRENT_TIMESTAMP),
    ('Regalería', lower(trim('Regalería')), 'approved', CURRENT_TIMESTAMP),
    ('Ferretería', lower(trim('Ferretería')), 'approved', CURRENT_TIMESTAMP),
    ('Pinturería', lower(trim('Pinturería')), 'approved', CURRENT_TIMESTAMP),
    ('Corralón', lower(trim('Corralón')), 'approved', CURRENT_TIMESTAMP),
    ('Electricidad', lower(trim('Electricidad')), 'approved', CURRENT_TIMESTAMP),
    ('Sanitarios', lower(trim('Sanitarios')), 'approved', CURRENT_TIMESTAMP),
    ('Mueblería', lower(trim('Mueblería')), 'approved', CURRENT_TIMESTAMP),
    ('Colchonería', lower(trim('Colchonería')), 'approved', CURRENT_TIMESTAMP),
    ('Decoración', lower(trim('Decoración')), 'approved', CURRENT_TIMESTAMP),
    ('Electrodomésticos', lower(trim('Electrodomésticos')), 'approved', CURRENT_TIMESTAMP),
    ('Tecnología', lower(trim('Tecnología')), 'approved', CURRENT_TIMESTAMP),
    ('Telefonía', lower(trim('Telefonía')), 'approved', CURRENT_TIMESTAMP),
    ('Computación', lower(trim('Computación')), 'approved', CURRENT_TIMESTAMP),
    ('Accesorios gamer', lower(trim('Accesorios gamer')), 'approved', CURRENT_TIMESTAMP),
    ('Bicicletería', lower(trim('Bicicletería')), 'approved', CURRENT_TIMESTAMP),
    ('Repuestos automotor', lower(trim('Repuestos automotor')), 'approved', CURRENT_TIMESTAMP),
    ('Gomería', lower(trim('Gomería')), 'approved', CURRENT_TIMESTAMP),
    ('Lavadero', lower(trim('Lavadero')), 'approved', CURRENT_TIMESTAMP),
    ('Veterinaria', lower(trim('Veterinaria')), 'approved', CURRENT_TIMESTAMP),
    ('Pet shop', lower(trim('Pet shop')), 'approved', CURRENT_TIMESTAMP),
    ('Peluquería', lower(trim('Peluquería')), 'approved', CURRENT_TIMESTAMP),
    ('Barbería', lower(trim('Barbería')), 'approved', CURRENT_TIMESTAMP),
    ('Estética', lower(trim('Estética')), 'approved', CURRENT_TIMESTAMP),
    ('Spa y masajes', lower(trim('Spa y masajes')), 'approved', CURRENT_TIMESTAMP),
    ('Gimnasio', lower(trim('Gimnasio')), 'approved', CURRENT_TIMESTAMP),
    ('Deportes', lower(trim('Deportes')), 'approved', CURRENT_TIMESTAMP),
    ('Estudio contable', lower(trim('Estudio contable')), 'approved', CURRENT_TIMESTAMP),
    ('Asesoría legal', lower(trim('Asesoría legal')), 'approved', CURRENT_TIMESTAMP),
    ('Inmobiliaria', lower(trim('Inmobiliaria')), 'approved', CURRENT_TIMESTAMP),
    ('Turismo', lower(trim('Turismo')), 'approved', CURRENT_TIMESTAMP),
    ('Eventos', lower(trim('Eventos')), 'approved', CURRENT_TIMESTAMP),
    ('Fotografía', lower(trim('Fotografía')), 'approved', CURRENT_TIMESTAMP),
    ('Imprenta', lower(trim('Imprenta')), 'approved', CURRENT_TIMESTAMP),
    ('Servicios de limpieza', lower(trim('Servicios de limpieza')), 'approved', CURRENT_TIMESTAMP),
    ('Cerrajería', lower(trim('Cerrajería')), 'approved', CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO offer_categories (name, normalized_name, status, created_at)
SELECT DISTINCT category, lower(trim(category)), 'approved', CURRENT_TIMESTAMP
FROM offers
WHERE trim(category) <> '';
